### ISSUE TITLE
yolov8 onnx如何导出多输出

### ISSUE THREAD

**Issue by Quser-l** [airockchip/rknn_model_zoo#101]
好像不支持这样[1,8,8400]的这种
![image](https://github.com/airockchip/rknn_model_zoo/assets/58429136/b0276bb3-caa5-4ed5-a1a5-a027ecced427)

![image](https://github.com/airockchip/rknn_model_zoo/assets/58429136/4f50ca47-1d53-46f4-b338-2ab64ecd4880)

**Comment by moyu026** [comment]
请问你解决了吗？我也遇到一样的问题

**Comment by airockchip** [comment]
参考：https://github.com/airockchip/ultralytics_yolov8
