### ISSUE TITLE
nms写得有问题

### ISSUE THREAD

**Issue by zhouyuanqi1** [airockchip/rknn_model_zoo#106]
![屏幕截图_48](https://github.com/airockchip/rknn_model_zoo/assets/72115187/625e7e11-2b68-4bf1-9b43-5a1c43a7aa15)
classID的索引不应该是validCount的顺序i，而应该indexArray[i]，因为快排时并没有做classID的排序。
应该改成如下：
![屏幕截图_49](https://github.com/airockchip/rknn_model_zoo/assets/72115187/962bc7f6-cf54-4b87-9288-797115a09c5c)
看看是否正确？

**Comment by Huntersdeng** [comment]
今天我也发现了这个问题，确实是要这样修改才正确！

**Comment by airockchip** [comment]
感谢您的反馈，v2.1.0版本已修复。
