### ISSUE TITLE
 RgaCollorFill(1756) RGA_COLORFILL fail: Invalid argument

### ISSUE THREAD

**Issue by DCC-lzhy** [airockchip/rknn_model_zoo#117]
src_box=(0 0 2559 1439)
dst_box=(0 84 383 299)
color=0x72
rga_api version 1.10.0_[2]
fill dst image (x y w h)=(0 0 384 384) with color=0x72727272
 RgaCollorFill(1756) RGA_COLORFILL fail: Invalid argument
 RgaCollorFill(1757) RGA_COLORFILL fail: Invalid argument
219 im2d_rga_impl rga_task_submit(2100): Failed to call RockChipRga interface, please use 'dmesg' command to view driver error log.

虽然报了这个错误，但不影响我的结果也，我看了这个函数，不知道怎么就是无效参数了。保存的输出图像是正确的。

**Comment by airockchip** [comment]
RGA宽高有对齐要求，参考：https://github.com/airockchip/librga/tree/main/docs 相关说明。可以先把这部分代码屏蔽掉。

**Comment by Digital2Slave** [comment]
> RGA宽高有对齐要求，参考：https://github.com/airockchip/librga/tree/main/docs 相关说明。可以先把这部分代码屏蔽掉。

具体屏蔽哪部分的代码呢？

**Comment by DCC-lzhy** [comment]
> RGA宽高有对齐要求，参考：https://github.com/airockchip/librga/tree/main/docs 相关说明。可以先把这部分代码屏蔽掉。

原来如此，多谢。

**Comment by vipslzyz** [comment]
> RGA宽高有对齐要求，参考：https://github.com/airockchip/librga/tree/main/docs 相关说明。可以先把这部分代码屏蔽掉。

我也有这问题，目前不影响结果，已按照文档说的对齐了宽高（stride 4 对齐），还是有这个报错。。。另外，请问如何屏蔽

src_box=(0 0 1919 1079)
dst_box=(0 140 639 499)
color=0x72
rga_api version 1.10.0_[2]
fill dst image (x y w h)=(0 0 640 640) with color=0x72727272
RgaCollorFill(1717) RGA_COLORFILL fail: Invalid argument
RgaCollorFill(1718) RGA_COLORFILL fail: Invalid argument

**Comment by Digital2Slave** [comment]
> > RGA宽高有对齐要求，参考：https://github.com/airockchip/librga/tree/main/docs 相关说明。可以先把这部分代码屏蔽掉。
> 
> 我也有这问题，目前不影响结果，已按照文档说的对齐了宽高（stride 4 对齐），还是有这个报错，rga版本1.8.1。。。另外，请问如何屏蔽
> 
> src_box=(0 0 1919 1079) dst_box=(0 140 639 499) color=0x72 fill dst image (x y w h)=(0 0 640 640) with color=0x72727272 RgaCollorFill(1717) RGA_COLORFILL fail: Invalid argument RgaCollorFill(1718) RGA_COLORFILL fail: Invalid argument

可能需要重新编译librga, https://github.com/airockchip/librga
你可以试试，我参考rknn-toolkit2/rknpu2/examples/rknn_yolov5_android_apk_demo，做了一个安卓库的demo, https://github.com/Digital2Slave/cv_npu。

**Comment by vipslzyz** [comment]
> > > RGA宽高有对齐要求，参考：https://github.com/airockchip/librga/tree/main/docs 相关说明。可以先把这部分代码屏蔽掉。
> > 
> > 
> > 我也有这问题，目前不影响结果，已按照文档说的对齐了宽高（stride 4 对齐），还是有这个报错，rga版本1.8.1。。。另外，请问如何屏蔽
> > src_box=(0 0 1919 1079) dst_box=(0 140 639 499) color=0x72 fill dst image (x y w h)=(0 0 640 640) with color=0x72727272 RgaCollorFill(1717) RGA_COLORFILL fail: Invalid argument RgaCollorFill(1718) RGA_COLORFILL fail: Invalid argument
> 
> 可能需要重新编译librga, https://github.com/airockchip/librga 你可以试试，我参考rknn-toolkit2/rknpu2/examples/rknn_yolov5_android_apk_demo，做了一个安卓库的demo, [https://github.com/Digital2Slave/cv_npu。](https://github.com/Digital2Slave/cv_npu%E3%80%82)

感谢解答，“可能需要重新编译librga, https://github.com/airockchip/librga“ 这个仓库里只有预编译的rga库，请问如何通过源码重新编译

**Comment by Digital2Slave** [comment]
> > > > RGA宽高有对齐要求，参考：https://github.com/airockchip/librga/tree/main/docs 相关说明。可以先把这部分代码屏蔽掉。
> > > 
> > > 
> > > 我也有这问题，目前不影响结果，已按照文档说的对齐了宽高（stride 4 对齐），还是有这个报错，rga版本1.8.1。。。另外，请问如何屏蔽
> > > src_box=(0 0 1919 1079) dst_box=(0 140 639 499) color=0x72 fill dst image (x y w h)=(0 0 640 640) with color=0x72727272 RgaCollorFill(1717) RGA_COLORFILL fail: Invalid argument RgaCollorFill(1718) RGA_COLORFILL fail: Invalid argument
> > 
> > 
> > 可能需要重新编译librga, https://github.com/airockchip/librga 你可以试试，我参考rknn-toolkit2/rknpu2/examples/rknn_yolov5_android_apk_demo，做了一个安卓库的demo, [https://github.com/Digital2Slave/cv_npu。](https://github.com/Digital2Slave/cv_npu%E3%80%82)
> 
> 感谢解答，“可能需要重新编译librga, [https://github.com/airockchip/librga“](https://github.com/airockchip/librga%E2%80%9C) 这个仓库里只有预编译的rga库，请问如何通过源码重新编译

可以问一下chatgpt-4o,how to build librga?

To build **librga** (Rockchip's RGA library), you typically follow these steps. **librga** is used to accelerate 2D graphics operations, and it's often used in embedded systems such as those with Rockchip processors.

Here’s a general process:

### Prerequisites:
1. **CMake**: Ensure that CMake is installed, as it is commonly used for building the project.
2. **Cross Compiler**: If you’re building for an embedded platform like an ARM-based Rockchip device, you'll need a cross compiler (e.g., `aarch64-linux-gnu-gcc` for ARM64).
3. **Dependencies**: Make sure you have necessary dependencies installed. These may include packages like `libdrm` or others depending on the platform.

### Steps to Build librga:

1. **Clone the repository:**
   First, you need to clone the librga GitHub repository:

   ```bash
   git clone https://github.com/rockchip-linux/libdrm-rockchip.git
   cd libdrm-rockchip
   ```

2. **Install Dependencies** (if on Ubuntu/Debian):

   ```bash
   sudo apt-get update
   sudo apt-get install libdrm-dev libudev-dev cmake build-essential pkg-config
   ```

3. **Create a build directory**:

   ```bash
   mkdir build
   cd build
   ```

4. **Generate build files using CMake**:

   If you’re building for the native platform (x86 for desktop or ARM on the embedded system):

   ```bash
   cmake ..
   ```

   If you’re cross-compiling for an embedded ARM platform (like Rockchip):

   ```bash
   cmake .. -DCMAKE_TOOLCHAIN_FILE=/path/to/your/toolchainfile.cmake
   ```

   The `toolchainfile.cmake` would specify the paths to the cross-compiler and any other necessary environment settings for cross-compilation.

5. **Build the project**:

   After generating the build files with CMake, compile the project:

   ```bash
   make
   ```

6. **Install** (optional, if you want to install it on your system):

   ```bash
   sudo make install
   ```

   This will typically install the library to `/usr/local/lib` or `/usr/lib`, depending on your system configuration.

### Common Issues:
- **Missing Dependencies**: Ensure that all required dependencies are installed, such as `libdrm`, which is essential for interfacing with the display hardware.
- **Cross-compilation**: If cross-compiling, make sure the paths to the compiler and libraries for the target architecture are correctly set in the toolchain file.

By following these steps, you should be able to build **librga** for your target platform. Let me know if you encounter any specific issues during the build!

**Comment by FreshmanMa** [comment]
你好，请问解决了？需要重编rga？ 我是调用improcess的时候 RGA_BLIT报错，并且得不到结果。

**Comment by trwstin** [comment]
当我设置图片的长跟阔是一样的值（简单说就是四方形），这个 bug 就解决了。虽然不是一个长期的解决方案，但至少代码可以运行。如果没有用RGA的需求，也可以直接去 image_utils.c 把 convert_image_rga() 换成 convert_image_cpu()。

**Comment by FreshmanMa** [comment]
> 当我设置图片的长跟阔是一样的值（简单说就是四方形），这个 bug 就解决了。虽然不是一个长期的解决方案，但至少代码可以运行。如果没有用RGA的需求，也可以直接去 image_utils.c 把 convert_image_rga() 换成 convert_image_cpu()。

我近期去尝试下，感谢！

**Comment by DCC-lzhy** [comment]
> 当我设置图片的长跟阔是一样的值（简单说就是四方形），这个 bug 就解决了。虽然不是一个长期的解决方案，但至少代码可以运行。如果没有用RGA的需求，也可以直接去 image_utils.c 把 convert_image_rga() 换成 convert_image_cpu()。

宽度应该是对齐到16

**Comment by ziyiflying** [comment]
我遇到了同样的问题（RgaCollorFill(1819)），跟代码发现不影响结果是因为执行了黄框里的拷贝动作而非imfill执行成功了
所以解决方法是将黄框里的内容复制到绿框位置即可。
报错原因未知，我更换了rga库也是一样的问题，替换了上面说的长等于宽（使其成为正方形）也是无效的。
![Image](https://github.com/user-attachments/assets/239f66b6-e973-4bac-aea0-c7ce45ed4f00)

**Comment by sr-feng** [comment]
@ziyiflying 我也像您这样使用，但出现了这个bug: Message from syslogd@firefly at Mar 27 10:23:28 ...
 kernel:[  614.193223] Internal error: Oops: 96000005 [#1] SMP

![Image](https://github.com/user-attachments/assets/71e4ff58-d083-4c81-8d6b-cc16a379d101)

**Comment by zhuimeng2080** [comment]
请教各位大佬，android 如何进行子线程调用rknn  yolov8函数呢，目前子线程调用一直出现崩溃状态。

**Comment by JensenHJS** [comment]
fill dst image (x y w h)=(0 0 384 384) with color=0x72727272
RgaCollorFill(1756) RGA_COLORFILL fail: Invalid argument
这个报错是图像宽高没符合对齐要求，然后是rga库中的打印，正常情况下需要注释rga库中的这些打印，并自行编rga库。另外也直接调用convert_image_cpu，但是如果src和dst的颜色空间不一致convert_image_cpu函数会直接返回，因此只能用convert_image_rga。给出一种不需要编rga库的解决办法，在convert_image_rga函数中修改为如下，就没有打印报错了。可以打断点到imfill函数处，报错打印就是imfill函数里的打印，且返回值是IM_STATUS_FAILED。

<img width="745" height="266" alt="Image" src="https://github.com/user-attachments/assets/0216b0dc-e473-4421-8c8f-d42523428595" />
