### ISSUE TITLE
提供下载的模型是已经训练好的吗

### ISSUE THREAD

**Issue by DreamArge** [airockchip/rknn_model_zoo#138]
如题，小白求问，下载后的模型是可以直接部署到板子上的吗

**Comment by Sos-Zachary** [comment]
@DreamArge 该仓库中提供的onnx模型是已经训练好的，可参考`example/`中对应模型的README文档，使用对应python脚本将onnx模型转换为rknn模型，即可使用rknn模型进行部署推理。
 同时，推荐阅读官方提供的参考文档，`01Quick_Start和`02User_Guide’,其中`01Quick_start`-第4章节运行示例程序详细描述了如何使用该仓库进行部署入门。文档目录如下https://github.com/airockchip/rknn-toolkit2/tree/master/doc。希望对你有所帮助LOL

**Comment by Sos-Zachary** [comment]
> 如题，小白求问，下载后的模型是可以直接部署到板子上的吗



> 如题，小白求问，下载后的模型是可以直接部署到板子上的吗

 @DreamArge 该仓库中提供的onnx模型是已经训练好的，可参考`example/`中对应模型的README文档，使用对应python脚本将onnx模型转换为rknn模型，即可使用rknn模型进行部署推理。
 同时，推荐阅读官方提供的参考文档，`01Quick_Start`和`02User_Guide`,其中`01Quick_start`第4章节"运行示例程序"详细描述了如何使用该仓库进行部署入门。文档目录如下https://github.com/airockchip/rknn-toolkit2/tree/master/doc, 希望对你有所帮助LoL

**Comment by DreamArge** [comment]
@Sos-Zachary 非常感谢！orz
