### ISSUE TITLE
如何更新3rdparty里的opencv库

### ISSUE THREAD

**Issue by HUST-WangZhimin** [airockchip/rknn_model_zoo#139]
现在3rdparty里的opencv文件是3.5版本的，我希望更新到4.0版本以上，请问需要怎么操作呢，给个方向或者关键词

**Comment by Sos-Zachary** [comment]
> 现在3rdparty里的opencv文件是3.5版本的，我希望更新到4.0版本以上，请问需要怎么操作呢，给个方向或者关键词


有个笨方法，不再使用3rdparty中的opencv库。可以在系统中编译安装自己想要的opencv版本，然后修改CMakelist文件对opencv相关依赖进行重新指定——依赖路径修改为刚刚新安装的路径，重新对代码进行编译，可以变相达到你的目的。
