### ISSUE TITLE
rknn_init 耗时过久有解决办法吗

### ISSUE THREAD

**Issue by DreamArge** [airockchip/rknn_model_zoo#141]
如题，请问 rknn_init 函数加载模型耗时过久，有什么解决方法吗？芯片是 rv1126 ，模型是 yolov8_seg.rknn，测了几次，耗时平均在98秒左右，cpu主频保持出厂设置

**Comment by DreamArge** [comment]
模型转换时的pre_compile 选项在rknn-toolkit 1.7.5 版本上无法使用，请问有什么改进方法吗

**Comment by DreamArge** [comment]
安装了1.7.3环境后，把pre_compile 选项选上，init耗时大幅降低了，很奇怪为什么 1.7.5 版本要砍去这个功能？demo 处理结果并无多大差别

**Comment by airockchip** [comment]
部分算子的支持变了，导致可能出现问题，可以使用在线预编译。
