### ISSUE TITLE
交叉编译器使用openeuler SDK编译yolov5应用报错

### ISSUE THREAD

**Issue by Suqier** [airockchip/rknn_model_zoo#142]
请教一个问题：
我在使用openeuler SDK编译yolov5应用的时候生成如下报错：
![image](https://github.com/user-attachments/assets/0bc13fb5-23ca-4439-b5b0-8f6beceaccee)
在尝试设置export LD_LIBRARY_PATH=/home/vboxuser/sdk/sysroots/armv8a-openeuler-linux/usr/lib64后仍然报此错误
此前使用openeuler SDK编译简单的hello world可通过
请问这应该咋办？

**Comment by airockchip** [comment]
编译工具链不匹配，无法简单支持，请提redmine issue
