### ISSUE TITLE
https://github.com/airockchip/rknn_model_zoo/tree/main/examples/mobilenet 这个在rv1106上也运行不起来

### ISSUE THREAD

**Issue by SindenDev** [airockchip/rknn_model_zoo#154]
[root@luckfox rknn_mobilenet_demo]# ./rknn_mobilenet_demo model/mobilenet_v2.rknn  model/bell.jpg
num_lines=1001
E RKNN: failed to decode config data!
Segmentation fault (core dumped)

**Comment by SindenDev** [comment]
库版本问题导致的

**Comment by pcb9382** [comment]
大佬我也遇到这个问题了，请问是什么版本库不一致导致的呢？

**Comment by pcb9382** [comment]
大佬我也遇到这个问题了，请问是什么版本库不一致导致的呢？

**Comment by pcb9382** [comment]
> 库版本问题导致的

大佬我也遇到这个问题了，请问是什么版本库不一致导致的呢？

**Comment by yehaoze** [comment]
> > 库版本问题导致的
> 
> 大佬我也遇到这个问题了，请问是什么版本库不一致导致的呢？

大佬，您好，我也遇到这个问题了，请问是什么方法解决的呢。
