### ISSUE TITLE
yolo系列中自己训练的模型转为onnx后如何转换成项目内model_comparison优化后的模型，可否提供脚本程序？

### ISSUE THREAD

**Issue by banniford** [airockchip/rknn_model_zoo#155]
我需要使用rknn，但我训练的模型转为onnx后应该如何优化裁减为项目中提供的onnx样式，可否提供脚本或转换方法，airockchip仓库内yolo7,yolo8和yolox并未更新最新的onnx导出，使用netron查看结构与项目内不符，可否提供脚本或优化方法。

**Comment by airockchip** [comment]
可以使用原工程导出onnx后，使用netron查看，找到后处理相关的节点（一般是concat后，可以先用onnxsim优化一下），用rknn.load_onnx指定输出节点。

**Comment by banniford** [comment]
> 可以使用原工程导出onnx后，使用netron查看，找到后处理相关的节点（一般是concat后，可以先用onnxsim优化一下），用rknn.load_onnx指定输出节点。

yolo系列的onnx是优化后的，有些节点是在导出时新添加进去的，并不是原本就有的，例如 yolo6 导出结点需要的ReduceSum节点[yolo6/model_comparison](https://github.com/airockchip/rknn_model_zoo/blob/main/examples/yolov6/model_comparison/yolov6_graph_comparison.jpg) 根据 https://github.com/airockchip/YOLOv6 仓库中 [export_onnx_for_rknn.py](https://github.com/airockchip/YOLOv6/blob/main/deploy/RKNN/export_onnx_for_rknn.py) 脚本导出并不能得到优化后的 onnx 节点

**Comment by banniford** [comment]
> 如果觉得麻烦，可以不加ReduceSum，直接稍微改一下后处理就好了。

好的，非常感谢！

**Comment by banniford** [comment]
找到问题了。训练的时候使用了参数--fuse_ab导致最后使用[export_onnx_for_rknn.py](https://github.com/airockchip/YOLOv6/blob/main/deploy/RKNN/export_onnx_for_rknn.py)导出的onnx与项目中的不符。
