### ISSUE TITLE
yolov8-pose导出onnx模型

### ISSUE THREAD

**Issue by Jerry-Handson** [airockchip/rknn_model_zoo#161]
目前使用[yolov8](https://github.com/airockchip/ultralytics_yolov8)代码导出的onnx文件与这里提供的onnx文件模型结构不一样，这里提供的onnx文件的导出方法什么时候会更新

**Comment by aodexiusi1997** [comment]
加急+++++++

**Comment by Jerry-Handson** [comment]
自己改了forward实现了
![image](https://github.com/user-attachments/assets/c41cce14-8832-4247-b5af-32a5d6db2165)

**Comment by Jerry-Handson** [comment]
自己修改Pose.forward实现了，只能用yolov8**n**-pose
![image](https://github.com/user-attachments/assets/633d12a1-7a16-4c5c-9fe4-3d8153fc404d)
