### ISSUE TITLE
rknn.inference爆内存

### ISSUE THREAD

**Issue by xuzhongming** [airockchip/rknn_model_zoo#162]
[问题描述]
用rknn_executor.py中的类RKNN_model_containner声明一个对象后，如果长时间多次调用类方法run()会使得内存慢慢增长，最终导致内存泄漏
 
[程序示例]
model = RKNN_model_containner( model_path, 'rk3588', None )
while True:
    outputs = model.run( input_data ) # 这一行

**Comment by SundaeOreo** [comment]
这个问题是如何解决的？
