### ISSUE TITLE
yolov10readme中的onnx和官方导出onnx检测头不一致

### ISSUE THREAD

**Issue by lmd670** [airockchip/rknn_model_zoo#168]
onnx转rknn格式的时候报错，后来发现yolov10 readme下载的onnx中head，和官方导出的head不一致

**Comment by CuberFan** [comment]
> onnx转rknn格式的时候报错，后来发现yolov10 readme下载的onnx中head，和官方导出的head不一致

和其他yolo算法一样，都是需要rockchip的研发人员修改，才能适配rockchip的NPU，等rockchip官方放出修改版的yolov10吧

**Comment by lmd670** [comment]
已经解决，官方修改可以参考https://github.com/airockchip/yolov10/tree/main的源码

**Comment by lmd670** [comment]
已经解决，官方修改可以参考[https://github.com/airockchip/yolov10/tree/main](https://github.com/airockchip/yolov10/tree/main%E7%9A%84%E6%BA%90%E7%A0%81)
