### ISSUE TITLE
yolov8_pose 按文档转 yolov8s_pose 的版本 无法出结果

### ISSUE THREAD

**Issue by 13fengfeng** [airockchip/rknn_model_zoo#178]
demo提供的yolov8n_pose .onnx转rknn后可以正常出结果，按文档丛https://github.com/airockchip/ultralytics_yolov8下载 yolov8s的转rknn后无结果输出

**Comment by Meky-hqd** [comment]
> demo提供的yolov8n_pose .onnx转rknn后可以正常出结果，按文档丛[https://github.com/airockchip/ultralytics_yolov8下载](https://github.com/airockchip/ultralytics_yolov8%E4%B8%8B%E8%BD%BD) yolov8s的转rknn后无结果输出

请问解决了吗？是不是yolov8官方提供的模型不能直接拿过来用？
