### ISSUE TITLE
Add Support for YOLOv11 Conversion to RKNN Format

### ISSUE THREAD

**Issue by shamspias** [airockchip/rknn_model_zoo#203]
Hello,

I would like to request the addition of **YOLOv11** model support in the RKNN Model Zoo. It would be great if you could provide a process or script for converting YOLOv11 models (either from `.pt` or `.onnx` format) to the **RKNN** format, similar to the existing support for YOLOv5 and YOLOv8.

### Specific Request:
- Include examples or tools for converting the **YOLOv11** model, particularly **YOLOv11.pt** or **YOLOv11.onnx** to **RKNN** format.
- Ensure compatibility with Rockchip NPU platforms such as **RK3568, RK3588**, and others.

Thank you for your continued efforts in supporting advanced AI models on Rockchip NPUs!

**Comment by zen-xingle** [comment]
Hello Shanmspias,

Thank you for your support and suggestions for RKNPU. The internal process is already processing the adaptation of the yolo11 model, which is expected to be released in the next update(mostly in one month)

**Comment by xinsuinizhuan** [comment]
hope see the rknn support the yolo11

**Comment by swdee** [comment]
Its now released in [version 2.3.0](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolo11)

**Comment by SisroCodeke** [comment]
> Its now released in [version 2.3.0](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolo11)

while i download the [https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt]yolov11 and converted that to onnx, (via convertor that provided by the airockchip/ultralytics_yolo11 , i found a [1x144x6400] connection (and then a conat of 1x144x8400) which was previously unsupported via rknn to onnx process.
do we still ganna face that same problem ???
since i could only convert the provided onnx model in the rknn-toolkit-zoo and any other onnx model converted via that pt file from the ultralytics_yolo11 wasnt successfull
can you help ?

**Comment by swdee** [comment]
> while i download the https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt yolov11 and converted that to onnx, (via convertor that provided by the airockchip/ultralytics_yolo11 , i found a [1x144x6400] connection (and then a concat of 1x144x8400) which was previously unsupported viaonnx to rknn process.

You need to read the information about the [YOLO models](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolo11) as Rockchip makes optimisations to them, so the outputs are different to what the Ultralytics models have.   This means you have to use [Rockchips fork](https://github.com/airockchip/ultralytics_yolo11) of the Ultralytics code based to train your model on.

**Comment by SisroCodeke** [comment]
> > while i download the https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt yolov11 and converted that to onnx, (via convertor that provided by the airockchip/ultralytics_yolo11 , i found a [1x144x6400] connection (and then a concat of 1x144x8400) which was previously unsupported viaonnx to rknn process.
> 
> You need to read the information about the [YOLO models](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolo11) as Rockchip makes optimisations to them, so the outputs are different to what the Ultralytics models have.   This means you have to use [Rockchips fork](https://github.com/airockchip/ultralytics_yolo11) of the Ultralytics code based to train your model on.

So I need to:
1- clone the ultralytics_yolo11
2- download the yolo11{n/s/...}
3- train it via ultralytics_yolo11/ultralytics/engine/trainer.py
4- convert the Trained model via ultralytics_yolo11/ultralytics/engine/exporter.py
5- convert it, via RKNN.api (with quantizasion_stp1 & stp2)
6- use it in rkXXXX chip via rknnlite.api

Am I right ?

**Comment by zoldaten** [comment]
> > > while i download the https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt yolov11 and converted that to onnx, (via convertor that provided by the airockchip/ultralytics_yolo11 , i found a [1x144x6400] connection (and then a concat of 1x144x8400) which was previously unsupported viaonnx to rknn process.
> > 
> > 
> > You need to read the information about the [YOLO models](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolo11) as Rockchip makes optimisations to them, so the outputs are different to what the Ultralytics models have.   This means you have to use [Rockchips fork](https://github.com/airockchip/ultralytics_yolo11) of the Ultralytics code based to train your model on.
> 
> So I need to: 1- clone the ultralytics_yolo11 2- download the yolo11{n/s/...} 3- train it via ultralytics_yolo11/ultralytics/engine/trainer.py 4- convert the Trained model via ultralytics_yolo11/ultralytics/engine/exporter.py 5- convert it, via RKNN.api (with quantizasion_stp1 & stp2) 6- use it in rkXXXX chip via rknnlite.api
> 
> Am I right ?

```
1. download yolov11n.pt
2. yolo export model=yolo11n.pt format=onnx (pip3 install ultralytics if u dont have yet)
3.  cd /rknn_model_zoo/examples/yolo11/python/
4. python3 convert.py  yolov11n.onnx rk3566
5. python3 yolo11.py --model_path yolo11.rknn --target rk3566
```
