### ISSUE TITLE
在yolov8示例程序中添加opencv组件异常

### ISSUE THREAD

**Issue by goodhomeire** [airockchip/rknn_model_zoo#216]
在yolov8 C API示例程序中添加opencv库异常，在CMkaeLists.txt中添加如下代码，报错找不到头文件：
```
#opencv
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
message(STATUS "64bit")
set (TARGET_LIB_ARCH lib64)
else()
message(STATUS "32bit")
set (TARGET_LIB_ARCH lib)
endif()
if (CMAKE_SYSTEM_NAME STREQUAL "Android")
  set(OpenCV_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../3rdparty/opencv/opencv-android-sdk-build/sdk/native/jni/abi-${CMAKE_ANDROID_ARCH_ABI})
else()
    if(TARGET_LIB_ARCH STREQUAL "lib")
      set(OpenCV_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../3rdparty/opencv/opencv-linux-armhf/share/OpenCV)
    else()
      set(OpenCV_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../3rdparty/opencv/opencv-linux-aarch64/share/OpenCV)
    endif()
endif()
find_package(OpenCV REQUIRED)
message(STATUS OpenCV_DIR=${OpenCV_DIR})
message(STATUS OpenCV_LIBS=${OpenCV_LIBS})
target_link_libraries(${PROJECT_NAME}
    imageutils
    fileutils
    imagedrawing    
    ${LIBRKNNRT}
    ${OpenCV_LIBS}    
    dl
)
```
```
fatal error: opencv2/core/core.hpp: No such file or directory
   27 | #include <opencv2/core/core.hpp>
```

加入如下代码后，报错找不到opencv函数的实现方法：
```
include_directories(${OpenCV_INCLUDE_DIRS})
```
```
main.cc.o: in function `cv::String::String(char const*)':
main.cc:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x48): undefined reference to `cv::String::allocate(unsigned long)'
/usr/bin/ld: CMakeFiles/rknn_yolov8_demo_zero_copy.dir/main.cc.o: in function `cv::Mat::~Mat()':
main.cc:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x74): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cc:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x88): undefined reference to `cv::Mat::deallocate()'
```
请教如何解决问题？

**Comment by goodhomeire** [comment]
目前已解决，不其额定是否为链接顺序问题：详情代码如下，未深究：
`cmake_minimum_required(VERSION 3.10)

project(rknn_yolov8_demo)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--allow-shlib-undefined")
if (ENABLE_ASAN)
	message(STATUS "BUILD WITH ADDRESS SANITIZER")
	set (CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
	set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
	set (CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
endif ()

set(rknpu_yolov8_file rknpu2/yolov8.cc)

# set(OpenCV_DIR ../../../3rdparty/opencv/opencv-linux-aarch64/share/OpenCV)
find_package(OpenCV CONFIG REQUIRED)
# include_directories(${OpenCV_INCLUDE_DIRS})

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../3rdparty/ 3rdparty.out)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../utils/ utils.out)

set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
file(GLOB SRCS ${CMAKE_CURRENT_SOURCE_DIR}/*.cc)

add_executable(${PROJECT_NAME}
    main.cc
    postprocess.cc
    ${rknpu_yolov8_file}
)
link_directories(${OpenCV_DIR}/../${TARGET_LIB_ARCH})
target_link_libraries(${PROJECT_NAME}
    imageutils
    fileutils
    imagedrawing    
    ${LIBRKNNRT}
    ${OpenCV_LIBS}
    dl
)
message(STATUS "OPENCV_LIB:${OpenCV_LIBS}")
if (CMAKE_SYSTEM_NAME STREQUAL "Android")
    target_link_libraries(${PROJECT_NAME}
    log
)
endif()

message(STATUS "!!!!!!!!!!!CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(THREADS_PREFER_PTHREAD_FLAG ON)
    find_package(Threads REQUIRED)
    find_package(OpenCV REQUIRED)
    target_link_libraries(${PROJECT_NAME} Threads::Threads)
endif()

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${LIBRKNNRT_INCLUDES}
)


# # Currently zero copy only supports rknpu2, v1103/rv1103b/rv1106 supports zero copy by default
# if (NOT (TARGET_SOC STREQUAL "rv1106" OR TARGET_SOC STREQUAL "rv1103" OR TARGET_SOC STREQUAL "rk1808" 
#     OR TARGET_SOC STREQUAL "rv1109" OR TARGET_SOC STREQUAL "rv1126" OR TARGET_SOC STREQUAL "rv1103b"))
#     add_executable(${PROJECT_NAME}_zero_copy
#         main.cc
#         postprocess.cc
#         rknpu2/yolov8_zero_copy.cc
#     )

#     target_compile_definitions(${PROJECT_NAME}_zero_copy PRIVATE ZERO_COPY)

#     target_link_libraries(${PROJECT_NAME}_zero_copy
#         imageutils
#         fileutils
#         imagedrawing    
#         ${LIBRKNNRT}
#         dl
#     )

#     if (CMAKE_SYSTEM_NAME STREQUAL "Android")
#         target_link_libraries(${PROJECT_NAME}_zero_copy
#         log
#     )
#     endif()

#     if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
#         set(THREADS_PREFER_PTHREAD_FLAG ON)
#         find_package(Threads REQUIRED)
#         target_link_libraries(${PROJECT_NAME}_zero_copy Threads::Threads)
#     endif()

#     target_include_directories(${PROJECT_NAME}_zero_copy PRIVATE
#         ${CMAKE_CURRENT_SOURCE_DIR}
#         ${LIBRKNNRT_INCLUDES}
#     )
#     install(TARGETS ${PROJECT_NAME}_zero_copy DESTINATION .)
# endif()

install(TARGETS ${PROJECT_NAME} DESTINATION .)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/../model/bus.jpg DESTINATION model)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/../model/coco_80_labels_list.txt DESTINATION model)
file(GLOB RKNN_FILES "${CMAKE_CURRENT_SOURCE_DIR}/../model/*.rknn")
install(FILES ${RKNN_FILES} DESTINATION model)`

**Comment by goodhomeire** [comment]
目前已解决，不确定是否为链接问题，为深究，具体如下：
```
cmake_minimum_required(VERSION 3.10)

project(rknn_yolov8_demo)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--allow-shlib-undefined")
if (ENABLE_ASAN)
	message(STATUS "BUILD WITH ADDRESS SANITIZER")
	set (CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
	set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
	set (CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
endif ()

set(rknpu_yolov8_file rknpu2/yolov8.cc)

# set(OpenCV_DIR ../../../3rdparty/opencv/opencv-linux-aarch64/share/OpenCV)
find_package(OpenCV CONFIG REQUIRED)
# include_directories(${OpenCV_INCLUDE_DIRS})

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../3rdparty/ 3rdparty.out)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../utils/ utils.out)

set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
file(GLOB SRCS ${CMAKE_CURRENT_SOURCE_DIR}/*.cc)

add_executable(${PROJECT_NAME}
    main.cc
    postprocess.cc
    ${rknpu_yolov8_file}
)
link_directories(${OpenCV_DIR}/../${TARGET_LIB_ARCH})
target_link_libraries(${PROJECT_NAME}
    imageutils
    fileutils
    imagedrawing    
    ${LIBRKNNRT}
    ${OpenCV_LIBS}
    dl
)
message(STATUS "OPENCV_LIB:${OpenCV_LIBS}")
if (CMAKE_SYSTEM_NAME STREQUAL "Android")
    target_link_libraries(${PROJECT_NAME}
    log
)
endif()

message(STATUS "!!!!!!!!!!!CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(THREADS_PREFER_PTHREAD_FLAG ON)
    find_package(Threads REQUIRED)
    find_package(OpenCV REQUIRED)
    target_link_libraries(${PROJECT_NAME} Threads::Threads)
endif()

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${LIBRKNNRT_INCLUDES}
)


# # Currently zero copy only supports rknpu2, v1103/rv1103b/rv1106 supports zero copy by default
# if (NOT (TARGET_SOC STREQUAL "rv1106" OR TARGET_SOC STREQUAL "rv1103" OR TARGET_SOC STREQUAL "rk1808" 
#     OR TARGET_SOC STREQUAL "rv1109" OR TARGET_SOC STREQUAL "rv1126" OR TARGET_SOC STREQUAL "rv1103b"))
#     add_executable(${PROJECT_NAME}_zero_copy
#         main.cc
#         postprocess.cc
#         rknpu2/yolov8_zero_copy.cc
#     )

#     target_compile_definitions(${PROJECT_NAME}_zero_copy PRIVATE ZERO_COPY)

#     target_link_libraries(${PROJECT_NAME}_zero_copy
#         imageutils
#         fileutils
#         imagedrawing    
#         ${LIBRKNNRT}
#         dl
#     )

#     if (CMAKE_SYSTEM_NAME STREQUAL "Android")
#         target_link_libraries(${PROJECT_NAME}_zero_copy
#         log
#     )
#     endif()

#     if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
#         set(THREADS_PREFER_PTHREAD_FLAG ON)
#         find_package(Threads REQUIRED)
#         target_link_libraries(${PROJECT_NAME}_zero_copy Threads::Threads)
#     endif()

#     target_include_directories(${PROJECT_NAME}_zero_copy PRIVATE
#         ${CMAKE_CURRENT_SOURCE_DIR}
#         ${LIBRKNNRT_INCLUDES}
#     )
#     install(TARGETS ${PROJECT_NAME}_zero_copy DESTINATION .)
# endif()

install(TARGETS ${PROJECT_NAME} DESTINATION .)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/../model/bus.jpg DESTINATION model)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/../model/coco_80_labels_list.txt DESTINATION model)
file(GLOB RKNN_FILES "${CMAKE_CURRENT_SOURCE_DIR}/../model/*.rknn")
install(FILES ${RKNN_FILES} DESTINATION model)
```

**Comment by Yaoxingtian** [comment]
> 目前已解决，不确定是否为链接问题，为深究，具体如下：
> 
> ```
> cmake_minimum_required(VERSION 3.10)
> 
> project(rknn_yolov8_demo)
> set(CMAKE_CXX_STANDARD 11)
> set(CMAKE_CXX_STANDARD_REQUIRED ON)
> set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--allow-shlib-undefined")
> if (ENABLE_ASAN)
> 	message(STATUS "BUILD WITH ADDRESS SANITIZER")
> 	set (CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
> 	set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
> 	set (CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
> endif ()
> 
> set(rknpu_yolov8_file rknpu2/yolov8.cc)
> 
> # set(OpenCV_DIR ../../../3rdparty/opencv/opencv-linux-aarch64/share/OpenCV)
> find_package(OpenCV CONFIG REQUIRED)
> # include_directories(${OpenCV_INCLUDE_DIRS})
> 
> add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../3rdparty/ 3rdparty.out)
> add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../utils/ utils.out)
> 
> set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
> file(GLOB SRCS ${CMAKE_CURRENT_SOURCE_DIR}/*.cc)
> 
> add_executable(${PROJECT_NAME}
>     main.cc
>     postprocess.cc
>     ${rknpu_yolov8_file}
> )
> link_directories(${OpenCV_DIR}/../${TARGET_LIB_ARCH})
> target_link_libraries(${PROJECT_NAME}
>     imageutils
>     fileutils
>     imagedrawing    
>     ${LIBRKNNRT}
>     ${OpenCV_LIBS}
>     dl
> )
> message(STATUS "OPENCV_LIB:${OpenCV_LIBS}")
> if (CMAKE_SYSTEM_NAME STREQUAL "Android")
>     target_link_libraries(${PROJECT_NAME}
>     log
> )
> endif()
> 
> message(STATUS "!!!!!!!!!!!CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
> if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
>     set(THREADS_PREFER_PTHREAD_FLAG ON)
>     find_package(Threads REQUIRED)
>     find_package(OpenCV REQUIRED)
>     target_link_libraries(${PROJECT_NAME} Threads::Threads)
> endif()
> 
> target_include_directories(${PROJECT_NAME} PRIVATE
>     ${CMAKE_CURRENT_SOURCE_DIR}
>     ${LIBRKNNRT_INCLUDES}
> )
> 
> 
> # # Currently zero copy only supports rknpu2, v1103/rv1103b/rv1106 supports zero copy by default
> # if (NOT (TARGET_SOC STREQUAL "rv1106" OR TARGET_SOC STREQUAL "rv1103" OR TARGET_SOC STREQUAL "rk1808" 
> #     OR TARGET_SOC STREQUAL "rv1109" OR TARGET_SOC STREQUAL "rv1126" OR TARGET_SOC STREQUAL "rv1103b"))
> #     add_executable(${PROJECT_NAME}_zero_copy
> #         main.cc
> #         postprocess.cc
> #         rknpu2/yolov8_zero_copy.cc
> #     )
> 
> #     target_compile_definitions(${PROJECT_NAME}_zero_copy PRIVATE ZERO_COPY)
> 
> #     target_link_libraries(${PROJECT_NAME}_zero_copy
> #         imageutils
> #         fileutils
> #         imagedrawing    
> #         ${LIBRKNNRT}
> #         dl
> #     )
> 
> #     if (CMAKE_SYSTEM_NAME STREQUAL "Android")
> #         target_link_libraries(${PROJECT_NAME}_zero_copy
> #         log
> #     )
> #     endif()
> 
> #     if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
> #         set(THREADS_PREFER_PTHREAD_FLAG ON)
> #         find_package(Threads REQUIRED)
> #         target_link_libraries(${PROJECT_NAME}_zero_copy Threads::Threads)
> #     endif()
> 
> #     target_include_directories(${PROJECT_NAME}_zero_copy PRIVATE
> #         ${CMAKE_CURRENT_SOURCE_DIR}
> #         ${LIBRKNNRT_INCLUDES}
> #     )
> #     install(TARGETS ${PROJECT_NAME}_zero_copy DESTINATION .)
> # endif()
> 
> install(TARGETS ${PROJECT_NAME} DESTINATION .)
> install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/../model/bus.jpg DESTINATION model)
> install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/../model/coco_80_labels_list.txt DESTINATION model)
> file(GLOB RKNN_FILES "${CMAKE_CURRENT_SOURCE_DIR}/../model/*.rknn")
> install(FILES ${RKNN_FILES} DESTINATION model)
> ```

请问你有用opencv 推理的demo吗
