### ISSUE TITLE
yolov8 seg后处理

### ISSUE THREAD

**Issue by ZH-1225** [airockchip/rknn_model_zoo#217]
分割后处理postprocess.cc文件的最后
`    uint8_t *cropped_seg_mask = (uint8_t *)malloc(cropped_height * cropped_width * sizeof(uint8_t));
    uint8_t *real_seg_mask = (uint8_t *)malloc(ori_in_height * ori_in_width * sizeof(uint8_t));
    seg_reverse(all_mask_in_one, cropped_seg_mask, real_seg_mask,
                model_in_height, model_in_width, cropped_height, cropped_width, ori_in_height, ori_in_width, y_pad, x_pad);
    od_results->results_seg[0].seg_mask = real_seg_mask;
    free(all_mask_in_one);
    free(cropped_seg_mask);
    free(seg_mask);
    free(matmul_out);
    free(real_seg_mask);
    timer.tok();
`
没有free(real_seg_mask)好像会导致内存泄漏

**Comment by jxx-xi** [comment]
> 分割后处理postprocess.cc文件的最后 ` uint8_t *cropped_seg_mask = (uint8_t *)malloc(cropped_height * cropped_width * sizeof(uint8_t)); uint8_t *real_seg_mask = (uint8_t *)malloc(ori_in_height * ori_in_width * sizeof(uint8_t)); seg_reverse(all_mask_in_one, cropped_seg_mask, real_seg_mask, model_in_height, model_in_width, cropped_height, cropped_width, ori_in_height, ori_in_width, y_pad, x_pad); od_results->results_seg[0].seg_mask = real_seg_mask; free(all_mask_in_one); free(cropped_seg_mask); free(seg_mask); free(matmul_out); free(real_seg_mask); timer.tok();` 没有free(real_seg_mask)好像会导致内存泄漏

已经在main中释放了

**Comment by ZH-1225** [comment]
> > 分割后处理postprocess.cc文件的最后 ` uint8_t *cropped_seg_mask = (uint8_t *)malloc(cropped_height * cropped_width * sizeof(uint8_t)); uint8_t *real_seg_mask = (uint8_t *)malloc(ori_in_height * ori_in_width * sizeof(uint8_t)); seg_reverse(all_mask_in_one, cropped_seg_mask, real_seg_mask, model_in_height, model_in_width, cropped_height, cropped_width, ori_in_height, ori_in_width, y_pad, x_pad); od_results->results_seg[0].seg_mask = real_seg_mask; free(all_mask_in_one); free(cropped_seg_mask); free(seg_mask); free(matmul_out); free(real_seg_mask); timer.tok();` 没有free(real_seg_mask)好像会导致内存泄漏
> 
> 已经在main中释放了

好的，感谢
