### ISSUE TITLE
zipformer编译3588 linux板卡失败

### ISSUE THREAD

**Issue by Mactarvish** [airockchip/rknn_model_zoo#220]
Ubuntu 22.04
c918ec6579494947e4e3b13816ae427d4270085f

编译yolov5是正常的：`./build-linux.sh -t rk3588 -a aarch64 -d yolov5`

但是编译zipformer失败：

```
./build-linux.sh -t rk3588 -a aarch64 -d zipformer
aarch64-linux-gnu
===================================
BUILD_DEMO_NAME=zipformer
BUILD_DEMO_PATH=examples/zipformer/cpp
TARGET_SOC=rk3588
TARGET_ARCH=aarch64
BUILD_TYPE=Release
ENABLE_ASAN=OFF
DISABLE_RGA=OFF
INSTALL_DIR=/home/john/third_party/rknn_model_zoo/install/rk3588_linux_aarch64/rknn_zipformer_demo
BUILD_DIR=/home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
CC=aarch64-linux-gnu-gcc
CXX=aarch64-linux-gnu-g++
===================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
Consolidate compiler generated dependencies of target audioutils
Consolidate compiler generated dependencies of target fileutils
Consolidate compiler generated dependencies of target imagedrawing
Consolidate compiler generated dependencies of target imageutils
[ 16%] Built target fileutils
[ 33%] Built target audioutils
[ 50%] Built target imageutils
[ 66%] Built target imagedrawing
Consolidate compiler generated dependencies of target rknn_zipformer_demo
[ 75%] Linking CXX executable rknn_zipformer_demo
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o)(.text._ZNK3knf12FbankOptions8ToStringB5cxx11Ev[_ZNK3knf12FbankOptions8ToStringB5cxx11Ev]+0x34): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21'
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: 最后的链结失败: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rknn_zipformer_demo.dir/build.make:134：rknn_zipformer_demo] 错误 1
make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/rknn_zipformer_demo.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

```

**Comment by jxx-xi** [comment]
> Ubuntu 22.04 [c918ec6](https://github.com/airockchip/rknn_model_zoo/commit/c918ec6579494947e4e3b13816ae427d4270085f)
> 
> 编译yolov5是正常的：`./build-linux.sh -t rk3588 -a aarch64 -d yolov5`
> 
> 但是编译zipformer失败：
> 
> ```
> ./build-linux.sh -t rk3588 -a aarch64 -d zipformer
> aarch64-linux-gnu
> ===================================
> BUILD_DEMO_NAME=zipformer
> BUILD_DEMO_PATH=examples/zipformer/cpp
> TARGET_SOC=rk3588
> TARGET_ARCH=aarch64
> BUILD_TYPE=Release
> ENABLE_ASAN=OFF
> DISABLE_RGA=OFF
> INSTALL_DIR=/home/john/third_party/rknn_model_zoo/install/rk3588_linux_aarch64/rknn_zipformer_demo
> BUILD_DIR=/home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> CC=aarch64-linux-gnu-gcc
> CXX=aarch64-linux-gnu-g++
> ===================================
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> Consolidate compiler generated dependencies of target audioutils
> Consolidate compiler generated dependencies of target fileutils
> Consolidate compiler generated dependencies of target imagedrawing
> Consolidate compiler generated dependencies of target imageutils
> [ 16%] Built target fileutils
> [ 33%] Built target audioutils
> [ 50%] Built target imageutils
> [ 66%] Built target imagedrawing
> Consolidate compiler generated dependencies of target rknn_zipformer_demo
> [ 75%] Linking CXX executable rknn_zipformer_demo
> /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
> /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o)(.text._ZNK3knf12FbankOptions8ToStringB5cxx11Ev[_ZNK3knf12FbankOptions8ToStringB5cxx11Ev]+0x34): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21'
> /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: 最后的链结失败: bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/rknn_zipformer_demo.dir/build.make:134：rknn_zipformer_demo] 错误 1
> make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/rknn_zipformer_demo.dir/all] 错误 2
> make: *** [Makefile:136：all] 错误 2
> ```

删掉build目录，然后参考此文档中的交叉编译器重新编一下：https://github.com/airockchip/rknn_model_zoo/blob/main/docs/Compilation_Environment_Setup_Guide_CN.md

**Comment by Mactarvish** [comment]
> > Ubuntu 22.04 [c918ec6](https://github.com/airockchip/rknn_model_zoo/commit/c918ec6579494947e4e3b13816ae427d4270085f)
> > 编译yolov5是正常的：`./build-linux.sh -t rk3588 -a aarch64 -d yolov5`
> > 但是编译zipformer失败：
> > ```
> > ./build-linux.sh -t rk3588 -a aarch64 -d zipformer
> > aarch64-linux-gnu
> > ===================================
> > BUILD_DEMO_NAME=zipformer
> > BUILD_DEMO_PATH=examples/zipformer/cpp
> > TARGET_SOC=rk3588
> > TARGET_ARCH=aarch64
> > BUILD_TYPE=Release
> > ENABLE_ASAN=OFF
> > DISABLE_RGA=OFF
> > INSTALL_DIR=/home/john/third_party/rknn_model_zoo/install/rk3588_linux_aarch64/rknn_zipformer_demo
> > BUILD_DIR=/home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > CC=aarch64-linux-gnu-gcc
> > CXX=aarch64-linux-gnu-g++
> > ===================================
> > -- Configuring done
> > -- Generating done
> > -- Build files have been written to: /home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > Consolidate compiler generated dependencies of target audioutils
> > Consolidate compiler generated dependencies of target fileutils
> > Consolidate compiler generated dependencies of target imagedrawing
> > Consolidate compiler generated dependencies of target imageutils
> > [ 16%] Built target fileutils
> > [ 33%] Built target audioutils
> > [ 50%] Built target imageutils
> > [ 66%] Built target imagedrawing
> > Consolidate compiler generated dependencies of target rknn_zipformer_demo
> > [ 75%] Linking CXX executable rknn_zipformer_demo
> > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
> > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o)(.text._ZNK3knf12FbankOptions8ToStringB5cxx11Ev[_ZNK3knf12FbankOptions8ToStringB5cxx11Ev]+0x34): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21'
> > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: 最后的链结失败: bad value
> > collect2: error: ld returned 1 exit status
> > make[2]: *** [CMakeFiles/rknn_zipformer_demo.dir/build.make:134：rknn_zipformer_demo] 错误 1
> > make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/rknn_zipformer_demo.dir/all] 错误 2
> > make: *** [Makefile:136：all] 错误 2
> > ```
> 
> 删掉build目录，然后参考此文档中的交叉编译器重新编一下：https://github.com/airockchip/rknn_model_zoo/blob/main/docs/Compilation_Environment_Setup_Guide_CN.md

谢谢回复，交叉编译的配置应该是没有问题的，mobilenet、yolov5、yolo11等都可以编译成功并且在嵌入式侧正常运行，只有zipformer在编译的时候出现这个错误。似乎是libkaldi-native-fbank-core.a在编译的时候存在问题。

**Comment by jxx-xi** [comment]
就是因为语音模型的第三方库比较特殊，如果你用的编译器版本和model zoo中默认使用的不一致就会编译失败
图形显示平台中心 江信禧
**********************************************************
公司：瑞芯微电子股份有限公司
地址：福建省福州市铜盘路软件大道89号软件园A区20号楼
邮编：350003
Tel: 0591-83991906转8804
***@***.***
******************************************************************************************************************************************
重要提示：本邮件及其附件含有仅供特定个人或目的使用的保密信息。若您并非该特定收件人或误收本邮件，请从系统中永久性删除本邮件及所有附件。瑞芯微电子股份有限公司拥有本邮件及附件的著作权及解释权，禁止任何未经授权或许可的披露、储存或复制本邮件及附件的行为。谢谢您的配合。
IMPORTANT NOTICE: The contents of this email and any attachments may contain information that is privileged, confidential. If you are not the intended recipient or receive it by mistaken, please delete the email in its entirety. Rockchip Electronics Co., Ltd. copyright and reserve all rights .It is strictly prohibited to disclose, copy or store the email  without any further authorization or license.Thank you.
*******************************************************************************************************************************************


---- 回复的原邮件 ----
发件人 Mactarvish ***@***.***> 发送日期 2024年11月18日 18:42 收件人 airockchip/rknn_model_zoo ***@***.***> 抄送人 jxx-xi ***@***.***>,
Comment ***@***.***> 主题 Re: [airockchip/rknn_model_zoo] zipformer编译3588 linux板卡失败 (Issue #220)  

Ubuntu 22.04 c918ec6
 编译yolov5是正常的：./build-linux.sh -t rk3588 -a aarch64 -d yolov5
 但是编译zipformer失败：
./build-linux.sh -t rk3588 -a aarch64 -d zipformer
aarch64-linux-gnu
===================================
BUILD_DEMO_NAME=zipformer
BUILD_DEMO_PATH=examples/zipformer/cpp
TARGET_SOC=rk3588
TARGET_ARCH=aarch64
BUILD_TYPE=Release
ENABLE_ASAN=OFF
DISABLE_RGA=OFF
INSTALL_DIR=/home/john/third_party/rknn_model_zoo/install/rk3588_linux_aarch64/rknn_zipformer_demo
BUILD_DIR=/home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
CC=aarch64-linux-gnu-gcc
CXX=aarch64-linux-gnu-g++
===================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
Consolidate compiler generated dependencies of target audioutils
Consolidate compiler generated dependencies of target fileutils
Consolidate compiler generated dependencies of target imagedrawing
Consolidate compiler generated dependencies of target imageutils
[ 16%] Built target fileutils
[ 33%] Built target audioutils
[ 50%] Built target imageutils
[ 66%] Built target imagedrawing
Consolidate compiler generated dependencies of target rknn_zipformer_demo
[ 75%] Linking CXX executable rknn_zipformer_demo
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o)(.text._ZNK3knf12FbankOptions8ToStringB5cxx11Ev[_ZNK3knf12FbankOptions8ToStringB5cxx11Ev]+0x34): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21'
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: 最后的链结失败: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rknn_zipformer_demo.dir/build.make:134：rknn_zipformer_demo] 错误 1
make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/rknn_zipformer_demo.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2
删掉build目录，然后参考此文档中的交叉编译器重新编一下：https://github.com/airockchip/rknn_model_zoo/blob/main/docs/Compilation_Environment_Setup_Guide_CN.md
谢谢回复，交叉编译的配置应该是没有问题的，mobilenet、yolov5、yolo11等都可以编译成功并且在嵌入式侧正常运行，只有zipformer在编译的时候出现这个错误。似乎是libkaldi-native-fbank-core.a在编译的时候存在问题。

**Comment by Mactarvish** [comment]
> > > > Ubuntu 22.04 [c918ec6](https://github.com/airockchip/rknn_model_zoo/commit/c918ec6579494947e4e3b13816ae427d4270085f)
> > > > 编译yolov5是正常的：`./build-linux.sh -t rk3588 -a aarch64 -d yolov5`
> > > > 但是编译zipformer失败：
> > > > ```
> > > > ./build-linux.sh -t rk3588 -a aarch64 -d zipformer
> > > > aarch64-linux-gnu
> > > > ===================================
> > > > BUILD_DEMO_NAME=zipformer
> > > > BUILD_DEMO_PATH=examples/zipformer/cpp
> > > > TARGET_SOC=rk3588
> > > > TARGET_ARCH=aarch64
> > > > BUILD_TYPE=Release
> > > > ENABLE_ASAN=OFF
> > > > DISABLE_RGA=OFF
> > > > INSTALL_DIR=/home/john/third_party/rknn_model_zoo/install/rk3588_linux_aarch64/rknn_zipformer_demo
> > > > BUILD_DIR=/home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > > > CC=aarch64-linux-gnu-gcc
> > > > CXX=aarch64-linux-gnu-g++
> > > > ===================================
> > > > -- Configuring done
> > > > -- Generating done
> > > > -- Build files have been written to: /home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > > > Consolidate compiler generated dependencies of target audioutils
> > > > Consolidate compiler generated dependencies of target fileutils
> > > > Consolidate compiler generated dependencies of target imagedrawing
> > > > Consolidate compiler generated dependencies of target imageutils
> > > > [ 16%] Built target fileutils
> > > > [ 33%] Built target audioutils
> > > > [ 50%] Built target imageutils
> > > > [ 66%] Built target imagedrawing
> > > > Consolidate compiler generated dependencies of target rknn_zipformer_demo
> > > > [ 75%] Linking CXX executable rknn_zipformer_demo
> > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
> > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o)(.text._ZNK3knf12FbankOptions8ToStringB5cxx11Ev[_ZNK3knf12FbankOptions8ToStringB5cxx11Ev]+0x34): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21'
> > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: 最后的链结失败: bad value
> > > > collect2: error: ld returned 1 exit status
> > > > make[2]: *** [CMakeFiles/rknn_zipformer_demo.dir/build.make:134：rknn_zipformer_demo] 错误 1
> > > > make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/rknn_zipformer_demo.dir/all] 错误 2
> > > > make: *** [Makefile:136：all] 错误 2
> > > > ```
> > > 
> > > 
> > > 删掉build目录，然后参考此文档中的交叉编译器重新编一下：https://github.com/airockchip/rknn_model_zoo/blob/main/docs/Compilation_Environment_Setup_Guide_CN.md
> > 
> > 
> > 谢谢回复，交叉编译的配置应该是没有问题的，mobilenet、yolov5、yolo11等都可以编译成功并且在嵌入式侧正常运行，只有zipformer在编译的时候出现这个错误。似乎是libkaldi-native-fbank-core.a在编译的时候存在问题。
> 
> 就是因为语音模型的第三方库比较特殊，如果你用的不是model zoo默认使用的编译器版本的话，就会编译失败

谢谢江老师指导，对齐到文档中的编译器版本就可以了。

**Comment by jxx-xi** [comment]
> > > > > Ubuntu 22.04 [c918ec6](https://github.com/airockchip/rknn_model_zoo/commit/c918ec6579494947e4e3b13816ae427d4270085f)
> > > > > 编译yolov5是正常的：`./build-linux.sh -t rk3588 -a aarch64 -d yolov5`
> > > > > 但是编译zipformer失败：
> > > > > ```
> > > > > ./build-linux.sh -t rk3588 -a aarch64 -d zipformer
> > > > > aarch64-linux-gnu
> > > > > ===================================
> > > > > BUILD_DEMO_NAME=zipformer
> > > > > BUILD_DEMO_PATH=examples/zipformer/cpp
> > > > > TARGET_SOC=rk3588
> > > > > TARGET_ARCH=aarch64
> > > > > BUILD_TYPE=Release
> > > > > ENABLE_ASAN=OFF
> > > > > DISABLE_RGA=OFF
> > > > > INSTALL_DIR=/home/john/third_party/rknn_model_zoo/install/rk3588_linux_aarch64/rknn_zipformer_demo
> > > > > BUILD_DIR=/home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > > > > CC=aarch64-linux-gnu-gcc
> > > > > CXX=aarch64-linux-gnu-g++
> > > > > ===================================
> > > > > -- Configuring done
> > > > > -- Generating done
> > > > > -- Build files have been written to: /home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > > > > Consolidate compiler generated dependencies of target audioutils
> > > > > Consolidate compiler generated dependencies of target fileutils
> > > > > Consolidate compiler generated dependencies of target imagedrawing
> > > > > Consolidate compiler generated dependencies of target imageutils
> > > > > [ 16%] Built target fileutils
> > > > > [ 33%] Built target audioutils
> > > > > [ 50%] Built target imageutils
> > > > > [ 66%] Built target imagedrawing
> > > > > Consolidate compiler generated dependencies of target rknn_zipformer_demo
> > > > > [ 75%] Linking CXX executable rknn_zipformer_demo
> > > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
> > > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o)(.text._ZNK3knf12FbankOptions8ToStringB5cxx11Ev[_ZNK3knf12FbankOptions8ToStringB5cxx11Ev]+0x34): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21'
> > > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: 最后的链结失败: bad value
> > > > > collect2: error: ld returned 1 exit status
> > > > > make[2]: *** [CMakeFiles/rknn_zipformer_demo.dir/build.make:134：rknn_zipformer_demo] 错误 1
> > > > > make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/rknn_zipformer_demo.dir/all] 错误 2
> > > > > make: *** [Makefile:136：all] 错误 2
> > > > > ```
> > > > 
> > > > 
> > > > 删掉build目录，然后参考此文档中的交叉编译器重新编一下：https://github.com/airockchip/rknn_model_zoo/blob/main/docs/Compilation_Environment_Setup_Guide_CN.md
> > > 
> > > 
> > > 谢谢回复，交叉编译的配置应该是没有问题的，mobilenet、yolov5、yolo11等都可以编译成功并且在嵌入式侧正常运行，只有zipformer在编译的时候出现这个错误。似乎是libkaldi-native-fbank-core.a在编译的时候存在问题。
> > 
> > 
> > 就是因为语音模型的第三方库比较特殊，如果你用的不是model zoo默认使用的编译器版本的话，就会编译失败
> 
> 大哥，再请教一下嗷，这个版本的编译器是不是不支持设置`CMAKE_SYSROOT`呢，我现在想把语音模型的demo修改为在线流式推理的，这样需要依赖到板子上的alsa(asound，依赖GLIBC_2.33)，我其它的项目中使用的编译器版本是11.4.0，使用该编译器版本构建的话手动指定一下`CMAKE_SYSROOT`让编译器去SYSROOT里自动查找板子上的asound库就可以链接成功，但是文档中的6.3.1版本配置了`CMAKE_SYSROOT`之后似乎不好使

你是在板子上编译demo的吗？为什么要让他自动查找呢，直接在cmake里面自己链接应该也可以吧

**Comment by Mactarvish** [comment]
> > > > > > Ubuntu 22.04 [c918ec6](https://github.com/airockchip/rknn_model_zoo/commit/c918ec6579494947e4e3b13816ae427d4270085f)
> > > > > > 编译yolov5是正常的：`./build-linux.sh -t rk3588 -a aarch64 -d yolov5`
> > > > > > 但是编译zipformer失败：
> > > > > > ```
> > > > > > ./build-linux.sh -t rk3588 -a aarch64 -d zipformer
> > > > > > aarch64-linux-gnu
> > > > > > ===================================
> > > > > > BUILD_DEMO_NAME=zipformer
> > > > > > BUILD_DEMO_PATH=examples/zipformer/cpp
> > > > > > TARGET_SOC=rk3588
> > > > > > TARGET_ARCH=aarch64
> > > > > > BUILD_TYPE=Release
> > > > > > ENABLE_ASAN=OFF
> > > > > > DISABLE_RGA=OFF
> > > > > > INSTALL_DIR=/home/john/third_party/rknn_model_zoo/install/rk3588_linux_aarch64/rknn_zipformer_demo
> > > > > > BUILD_DIR=/home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > > > > > CC=aarch64-linux-gnu-gcc
> > > > > > CXX=aarch64-linux-gnu-g++
> > > > > > ===================================
> > > > > > -- Configuring done
> > > > > > -- Generating done
> > > > > > -- Build files have been written to: /home/john/third_party/rknn_model_zoo/build/build_rknn_zipformer_demo_rk3588_linux_aarch64_Release
> > > > > > Consolidate compiler generated dependencies of target audioutils
> > > > > > Consolidate compiler generated dependencies of target fileutils
> > > > > > Consolidate compiler generated dependencies of target imagedrawing
> > > > > > Consolidate compiler generated dependencies of target imageutils
> > > > > > [ 16%] Built target fileutils
> > > > > > [ 33%] Built target audioutils
> > > > > > [ 50%] Built target imageutils
> > > > > > [ 66%] Built target imagedrawing
> > > > > > Consolidate compiler generated dependencies of target rknn_zipformer_demo
> > > > > > [ 75%] Linking CXX executable rknn_zipformer_demo
> > > > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
> > > > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: /home/john/third_party/rknn_model_zoo/3rdparty/kaldi_native_fbank/Linux/aarch64/libkaldi-native-fbank-core.a(feature-fbank.cc.o)(.text._ZNK3knf12FbankOptions8ToStringB5cxx11Ev[_ZNK3knf12FbankOptions8ToStringB5cxx11Ev]+0x34): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21'
> > > > > > /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: 最后的链结失败: bad value
> > > > > > collect2: error: ld returned 1 exit status
> > > > > > make[2]: *** [CMakeFiles/rknn_zipformer_demo.dir/build.make:134：rknn_zipformer_demo] 错误 1
> > > > > > make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/rknn_zipformer_demo.dir/all] 错误 2
> > > > > > make: *** [Makefile:136：all] 错误 2
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 删掉build目录，然后参考此文档中的交叉编译器重新编一下：https://github.com/airockchip/rknn_model_zoo/blob/main/docs/Compilation_Environment_Setup_Guide_CN.md
> > > > 
> > > > 
> > > > 谢谢回复，交叉编译的配置应该是没有问题的，mobilenet、yolov5、yolo11等都可以编译成功并且在嵌入式侧正常运行，只有zipformer在编译的时候出现这个错误。似乎是libkaldi-native-fbank-core.a在编译的时候存在问题。
> > > 
> > > 
> > > 就是因为语音模型的第三方库比较特殊，如果你用的不是model zoo默认使用的编译器版本的话，就会编译失败
> > 
> > 
> > 大哥，再请教一下嗷，这个版本的编译器是不是不支持设置`CMAKE_SYSROOT`呢，我现在想把语音模型的demo修改为在线流式推理的，这样需要依赖到板子上的alsa(asound，依赖GLIBC_2.33)，我其它的项目中使用的编译器版本是11.4.0，使用该编译器版本构建的话手动指定一下`CMAKE_SYSROOT`让编译器去SYSROOT里自动查找板子上的asound库就可以链接成功，但是文档中的6.3.1版本配置了`CMAKE_SYSROOT`之后似乎不好使
> 
> 你是在板子上编译demo的吗？为什么要让他自动查找呢，直接在cmake里面自己链接应该也可以吧

不是的，我在pc上交叉编译板子上的demo，现在看来应该是编译器版本比较低对sysroot支持可能有点问题，最后通过重新编译kaldi fbank库解决了，多谢

**Comment by csukuangfj** [comment]
@Mactarvish 

sherpa-onnx 已经支持 rknn 了。

你可以用我们编译好的
- https://k2-fsa.github.io/sherpa/onnx/rk-npu-cn.html
- https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.11.1/sherpa-onnx-v1.11.1-rknn-linux-aarch64-shared.tar.bz2
- https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.11.1/sherpa-onnx-v1.11.1-rknn-linux-aarch64-static.tar.bz2


或者用
https://github.com/k2-fsa/sherpa-onnx/blob/master/build-rknn-linux-aarch64.sh
自己从源码编译
