### ISSUE TITLE
yolov8-seg分割效果C和Python不一致

### ISSUE THREAD

**Issue by wantao1008hh** [airockchip/rknn_model_zoo#251]
做的书脊分割。同样的模型，效果不一样，看样子是C代码处理的问题，但是不清楚问题在哪。
这是C版本代码，二值化的掩膜图片
![mask_copy](https://github.com/user-attachments/assets/0e0a9504-f3dd-4dd4-bd50-fa205750bd05)

这是Python 版本代码 ，修改了post_process中的seg_threadhold = 0.7，原来为0.5，改成0.7了。 即使0.5，也比C版本的好
![IMG_20191014_212538_binary_mask](https://github.com/user-attachments/assets/cc6ea4d2-5ca5-4305-9b4d-62de61950e48)

尝试方案 修改 C代码的矩阵乘积计算，还是无效：
`
void matmul_by_cpu_uint8_opencv(std::vector<float> &A, float *B, uint8_t *C, int ROWS_A, int COLS_A, int COLS_B) {
    // 将 A 和 B 转换为 cv::Mat
    cv::Mat matA(ROWS_A, COLS_A, CV_32F, A.data());  // A 是 std::vector<float>，转换为 cv::Mat
    cv::Mat matB(COLS_A, COLS_B, CV_32F, B);         // B 是原始指针，转换为 cv::Mat

    // 执行矩阵乘法
    cv::Mat matC;
    cv::gemm(matA, matB, 1.0, cv::Mat(), 0.0, matC);

    // 计算 Sigmoid: 1.0 / (1.0 + exp(-matC))
    cv::Mat matSigmoid;
    cv::exp(-matC, matSigmoid);  // 计算 exp(-matC)

    // Sigmoid = 1 / (1 + exp(-matC))
    matSigmoid = 1.0 / (1.0 + matSigmoid);

    // 阈值化操作: 大于 0.7 设置为 1，其它为 0
    cv::Mat matThresholded;
    cv::threshold(matSigmoid, matThresholded, 0.7, 1, cv::THRESH_BINARY);

    // 将 Sigmoid 后的 matSigmoid 转换为 uint8_t 类型 (范围 [0, 255])
    matThresholded.convertTo(matThresholded, CV_8U, 255.0);  // 将浮点数转为 uint8_t，范围是 [0, 255]

    // 将处理后的 matSigmoid 转回 C 数组
    std::memcpy(C, matThresholded.data, ROWS_A * COLS_B * sizeof(uint8_t));
}
`

**Comment by jxx-xi** [comment]
试试把 postprocess.cc 中的 // #define USE_FP_RESIZE 这个宏打开，用resize_by_opencv_fp试试

**Comment by wantao1008hh** [comment]
是的，计算时精度的问题。感谢。

**Comment by lixiari** [comment]
你好，请问所指的post_process中的seg_threadhold 这个值指的是什么，没有这个定义吧？
