### ISSUE TITLE
函数缺少返回值

### ISSUE THREAD

**Issue by eleclong** [airockchip/rknn_model_zoo#3]
pytorch/RKNN_C_demo/RKNN_toolkit_1/rknn_yolov5_demo/src/rga_func.c
int RGA_deinit(rga_context *rga_ctx)
{
    if(rga_ctx->rga_handle)
    {
        dlclose(rga_ctx->rga_handle);
        rga_ctx->rga_handle = NULL;
    }
}

**Comment by whoyh** [comment]
I tested it, why was  no error reported
