### ISSUE TITLE
Problem with cyclic import of Optimizer module

### ISSUE THREAD

**Issue by eleprog** [airockchip/rknn_model_zoo#43]
![image](https://github.com/airockchip/rknn_model_zoo/assets/116138692/5cff7b8d-c6f6-4100-9721-49fdfaf0e5a4)

**Comment by ShakhzodbekYuldoshov** [comment]
Same error have you found its solution.
I am using conda environment with 3.8 python version installed tensorflow==2.2.0. There is no version less that that in my case. Using Ubuntu 20.04, python3.8, conda environment, tensorflow=2.2.0, torch=1.10.0(installed using conda install), torchvision=0.11.0, mxnet-cu101==1.5.0. 

Can anyone help to solve it or do anyone have another environment where yolov5 converter worked?

**Comment by rkunpeng** [comment]
我也被这个问题困扰了多日，然后通过修改文件【rknn/base/acuitylib/__init__.py】注释掉两行代码，解决了该问题。具体位置如下图。
![image](https://github.com/airockchip/rknn_model_zoo/assets/17607869/412d9282-1149-49c8-882e-b43b9484ea72)

**Comment by ShakhzodbekYuldoshov** [comment]
@rkunpeng Worked! Thank you very much!
