### ISSUE TITLE
Yolo C_demo编译出问题

### ISSUE THREAD

**Issue by A-cvprogrammer** [airockchip/rknn_model_zoo#52]
报错，链接libpng.a库文件出问题
![Snipaste_2023-12-09_19-57-53](https://github.com/airockchip/rknn_model_zoo/assets/91362560/d4055af8-4af6-45c7-9585-162401b1ecd7)
![Snipaste_2023-12-09_20-00-15](https://github.com/airockchip/rknn_model_zoo/assets/91362560/108baf75-c9d1-47b6-b94c-d00600b94444)

**Comment by Yajian-Liu** [comment]
![Uploading Snipaste_2023-12-09_20-00-15.png…]()

**Comment by A-cvprogrammer** [comment]
已解决，自己编译，再将编译好的文件替换
