### ISSUE TITLE
请问有resnet, mobilenet, yolo各个模型在RV1126板子上的性能表现吗？为啥感觉性能不像标的有2T算力？

### ISSUE THREAD

**Issue by lishang06** [airockchip/rknn_model_zoo#74]
rv1126标的2T的npu算力，为啥模型的效果和同算力的HI3516DV500相差那么多啊？resnet50(256x256)在海思推理9ms, rv1126上42ms, mobilenet_v2(256x256)在海思上1.66ms, rv1126上4.46ms，yolov5s(640x640)海思上21ms，rv1126是67ms，普遍相差3左右的效率，感觉还不如在3562/3568板子1T的算力呢，网上也没有相关的对比测试资料，请问是什么原因啊

**Comment by krgbs** [comment]
我这rk3588的npu还没有i3100fcpu跑的快，谁知道他这啥玩应

**Comment by krgbs** [comment]
话说你yolov8n-pose模型转换成功了吗，如果成功了，麻烦你把转换过程开源一下，急需，谢谢
