### ISSUE TITLE
rk3588 转化transformer模型 efficientvit fp16时，出现提示：emitCHW_C1HWC2_regtasks: not aligned

### ISSUE THREAD

**Issue by DestinyMy** [airockchip/rknn_model_zoo#82]
在将**transformer模型efficientvit进行fp16的模型转换**时，未报错，但出现下面的提示</br>
W __init__: rknn-toolkit2 version: 1.6.0+81f21f4d
W load_onnx: It is recommended onnx opset 19, but your onnx model opset is 12!
W load_onnx: Model converted from pytorch, 'opset_version' should be set 19 in torch.onnx.export for successful convert!
Loading : 100%|████████████████████████████████████████████████| 100/100 [00:00<00:00, 75477.85it/s]
E RKNN: [02:20:21.409] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.409] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.409] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.409] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.409] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.410] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.423] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.424] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.424] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.424] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.424] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.424] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.424] emitCHW_C1HWC2_regtasks: not aligned
E RKNN: [02:20:21.424] emitCHW_C1HWC2_regtasks: not aligned</br></br>在3588上推理该fp16模型时，查看特征tensor信息，</br>D RKNN: [02:29:06.476]                                               Feature Tensor Information Table                                      
D RKNN: [02:29:06.476] ----------------------------------------------------------------------------------------------------------+---------------------------------
D RKNN: [02:29:06.476] ID  User           Tensor                           DataType  DataFormat   OrigShape      NativeShape     |     [Start       End)       Size
D RKNN: [02:29:06.476] ----------------------------------------------------------------------------------------------------------+---------------------------------
D RKNN: [02:29:06.476] 1   ConvHardSwish  images                           FLOAT16   NC1HWC2      (1,3,256,256)  (1,1,256,256,3) | 0xf6ac0000 0xf6b20000 0x00060000
D RKNN: [02:29:06.476] 2   ConvHardSwish  input.8                          FLOAT16   NC1HWC2      (1,8,128,128)  (1,4,128,128,8) | 0xf6b20000 0xf6c20000 0x00100000
D RKNN: [02:29:06.476] 3   ConvAdd        input.20                         FLOAT16   NC1HWC2      (1,8,128,128)  (1,8,128,128,8) | 0xf6c20000 0xf6e20000 0x00200000
D RKNN: [02:29:06.476] 3   ConvAdd        input.8                          FLOAT16   NC1HWC2      (1,8,128,128)  (1,4,128,128,8) | 0xf6b20000 0xf6c20000 0x00100000
D RKNN: [02:29:06.476] 4   ConvHardSwish  input.28                         FLOAT16   NC1HWC2      (1,8,128,128)  (1,2,128,128,8) | 0xf6e20000*0xf6ea0000 0x00080000
D RKNN: [02:29:06.476] 5   ConvHardSwish  input.40                         FLOAT16   NC1HWC2      (1,32,128,128) (1,8,128,128,8) | 0xf6ac0000 0xf6cc0000 0x00200000
D RKNN: [02:29:06.476] 6   Conv           input.52                         FLOAT16   NC1HWC2      (1,32,64,64)   (1,8,64,64,8)   | 0xf6cc0000 0xf6d40000 0x00080000
D RKNN: [02:29:06.476] 7   ConvHardSwish  input.60                         FLOAT16   NC1HWC2      (1,16,64,64)   (1,2,64,64,8)   | 0xf6ac0000 0xf6ae0000 0x00020000
D RKNN: [02:29:06.476] 8   ConvHardSwish  input.72                         FLOAT16   NC1HWC2      (1,64,64,64)   (1,16,64,64,8)  | 0xf6ae0000 0xf6be0000 0x00100000
D RKNN: [02:29:06.476] 9   ConvAdd        input.84                         FLOAT16   NC1HWC2      (1,64,64,64)   (1,16,64,64,8)  | 0xf6be0000 0xf6ce0000 0x00100000
D RKNN: [02:29:06.476] 9   ConvAdd        input.60                         FLOAT16   NC1HWC2      (1,16,64,64)   (1,2,64,64,8)   | 0xf6ac0000 0xf6ae0000 0x00020000
D RKNN: [02:29:06.476] 10  OutputOperator output                           FLOAT16   NC1HWC2      (1,16,64,64)   (1,2,64,64,8)   | 0xf6ae0000 0xf6b00000 0x00020000
D RKNN: [02:29:06.476] 11  ConvHardSwish  output                           FLOAT16   NC1HWC2      (1,16,64,64)   (1,2,64,64,8)   | 0xf6ae0000 0xf6b00000 0x00020000
</br>发现几乎所有层的数据格式均为NC1HWC2，并且有两个shape，其中OrigShape对应onnx的原始shape，**请问NativeShape是什么意思？因为这个shape也不单纯是原始shape进行切块拼接而成。另外转换时出现的emitCHW_C1HWC2_regtasks: not aligned提示会对最终的结果存在影响吗？**

**Comment by zen-xingle** [comment]
RKNN-Toolkit2 2.0.0 版本已经发布，请尝试使用新版本转模型解决此问题，之后如果还有问题请在 https://github.com/airockchip/rknn-toolkit2 提issue，这个问题和 RKNN-Toolkit2 关系大一些，和 rknn_model_zoo 不相关
