### ISSUE TITLE
调用OpenCV摄像头进行实时推理，但是显示器显示黑屏？

### ISSUE THREAD

**Issue by Eaglewzw** [airockchip/rknn_model_zoo#83]
在我进行摄像头实时推理的过程中，我先单独测试OpenCV的摄像头的显示效果，效果是正常的。但是当我加入推理代码后，显示窗口变黑屏了，窗口打印如下：
![bb](https://github.com/airockchip/rknn_model_zoo/assets/33340097/40de609a-c602-4138-9a30-0736cbd0fd27)
当我屏蔽以下代码，显示便正常了。
![图片1](https://github.com/airockchip/rknn_model_zoo/assets/33340097/79cbcfad-a11d-4ede-87f3-5d92c7728c37)
为何这两行代码会影响OpenCv摄像头的调用。

**Comment by XIEdeda** [comment]
我也遇到同样的问题了，请问你解决了吗？就是只要调用image_utils.c里面的函数就会有问题，包括用opencv读取图像，读取的图像为空，感觉是哪里冲突了。

**Comment by Eaglewzw** [comment]
原因是这里是使用RK3588的硬件模块RGA来求这个图片的letter box，改成软件的就好了。下面的代码仅供参考。
```
cv::Mat resized_image;
std::vector<float> pad;
resized_image = letterbox(ori_img, 640, 640, pad); 
letter_box.x_pad = pad[0];
letter_box.y_pad = pad[1];
letter_box.scale = pad[2];       



dst_img.width         = resized_image.cols;
dst_img.height        = resized_image.rows;
dst_img.width_stride  = resized_image.step;                          // 步幅等于每行的字节数
dst_img.height_stride = resized_image.rows;                          // 此处简化处理，实际情况可能需要调整
dst_img.format        = IMAGE_FORMAT_RGB888;                             
dst_img.size          = resized_image.total() * resized_image.elemSize();
dst_img.virt_addr     = resized_image.data;  
```




```
cv::Mat letterbox(cv::Mat &src, int h, int w, std::vector<float> &pad)
{

    int in_w = src.cols; // width
    int in_h = src.rows; // height
    int tar_w = w;
    int tar_h = h;
    float r = std::min(float(tar_h) / in_h, float(tar_w) / in_w);
    int inside_w = round(in_w * r);
    int inside_h = round(in_h * r);
    int pad_w = tar_w - inside_w;
    int pad_h = tar_h - inside_h;

    cv::Mat resize_img;

    cv::resize(src, resize_img, cv::Size(inside_w, inside_h));

    pad_w = pad_w / 2;
    pad_h = pad_h / 2;

    pad.push_back(pad_w);
    pad.push_back(pad_h);
    pad.push_back(r);

    int top = int(round(pad_h - 0.1));
    int bottom = int(round(pad_h + 0.1));
    int left = int(round(pad_w - 0.1));
    int right = int(round(pad_w + 0.1));
    cv::copyMakeBorder(resize_img, resize_img, top, bottom, left, right, 0, cv::Scalar(114, 114, 114));

    return resize_img;
}
```

**Comment by Yaoxingtian** [comment]
> 原因是这里是使用RK3588的硬件模块RGA来求这个图片的letter box，改成软件的就好了。下面的代码仅供参考。
> 
> ```
> cv::Mat resized_image;
> std::vector<float> pad;
> resized_image = letterbox(ori_img, 640, 640, pad); 
> letter_box.x_pad = pad[0];
> letter_box.y_pad = pad[1];
> letter_box.scale = pad[2];       
> 
> 
> 
> dst_img.width         = resized_image.cols;
> dst_img.height        = resized_image.rows;
> dst_img.width_stride  = resized_image.step;                          // 步幅等于每行的字节数
> dst_img.height_stride = resized_image.rows;                          // 此处简化处理，实际情况可能需要调整
> dst_img.format        = IMAGE_FORMAT_RGB888;                             
> dst_img.size          = resized_image.total() * resized_image.elemSize();
> dst_img.virt_addr     = resized_image.data;  
> ```
> 
> ```
> cv::Mat letterbox(cv::Mat &src, int h, int w, std::vector<float> &pad)
> {
> 
>     int in_w = src.cols; // width
>     int in_h = src.rows; // height
>     int tar_w = w;
>     int tar_h = h;
>     float r = std::min(float(tar_h) / in_h, float(tar_w) / in_w);
>     int inside_w = round(in_w * r);
>     int inside_h = round(in_h * r);
>     int pad_w = tar_w - inside_w;
>     int pad_h = tar_h - inside_h;
> 
>     cv::Mat resize_img;
> 
>     cv::resize(src, resize_img, cv::Size(inside_w, inside_h));
> 
>     pad_w = pad_w / 2;
>     pad_h = pad_h / 2;
> 
>     pad.push_back(pad_w);
>     pad.push_back(pad_h);
>     pad.push_back(r);
> 
>     int top = int(round(pad_h - 0.1));
>     int bottom = int(round(pad_h + 0.1));
>     int left = int(round(pad_w - 0.1));
>     int right = int(round(pad_w + 0.1));
>     cv::copyMakeBorder(resize_img, resize_img, top, bottom, left, right, 0, cv::Scalar(114, 114, 114));
> 
>     return resize_img;
> }
> ```
请问可以分享一下使用opencv推理的demo吗
