### ISSUE TITLE
百度网盘链接无法下载

### ISSUE THREAD

**Issue by jia0511** [airockchip/rknn_model_zoo#88]
https://github.com/airockchip/rknn_model_zoo/tree/v1.5.0/models/CV/object_detection/yolo/RKNN_C_demo/RKNN_toolkit_1/rknn_yolo_demo
![image](https://github.com/airockchip/rknn_model_zoo/assets/24822418/aa68f4fd-2b30-432c-8d55-0ef406c85c86)

**Comment by jia0511** [comment]
这个问题有人处理吗？

**Comment by zen-xingle** [comment]
https://github.com/airockchip/rknn_model_zoo/issues/87 重复问题，请参考issue-87
