### ISSUE TITLE
请问有计划支持rv1106跑ppocr吗

### ISSUE THREAD

**Issue by flamebox** [airockchip/rknn_model_zoo#89]
现在发现转换rknn时，ppocr-det没有问题，ppocr-rec模型则提示平台不支持rv1106。
请问后续有计划实现rv1106跑ppocr模型吗？现在我只能用ncnn跑，速度感人

**Comment by sajdlkasj** [comment]
模型转换没问题det的但是不能用把，我之前试过

**Comment by airockchip** [comment]
目前没有计划。
