### ISSUE TITLE
请问一下能否适配一下yolov8-pose,对我们很有用，谢谢。

### ISSUE THREAD

**Issue by fangyynb** [airockchip/rknn_model_zoo#97]
请问一下能否适配一下yolov8-pose,对我们很有用，谢谢。

**Comment by fangyynb** [comment]
现在导入yolov8onnx文件会导致转化失败

**Comment by satisl** [comment]
我们这边希望能够适配一下yolov8-obb

**Comment by HaoranShivs** [comment]
我正在尝试移植yolov8-pose，使用的是Ultralytics的预训练模型和手册里边所写的标准模型转化方式，转化过程没有报错。但是我遇到了问题，我模型最后出来结果的人体检测框和关键点出现按比例缩小（如缩小2-3倍），位置发生了漂移，与图中的人体和关键点不匹配，也出现了在图中均匀分散的冗余结果（如多了11倍的检测框）。但是所检测的关键点之间的关系确实正确的，即可以看出姿势的检测是对的。如下图。
![R-C](https://github.com/airockchip/rknn_model_zoo/assets/44091523/37c6e96c-90d3-4f30-8b14-8a96cce29bf3)
我控制变量验证过，不是图片前处理和后处理的问题，这个可以保证。我分析可能是最后一部分，即视野较大的卷积一直到结尾那里发生了权重重复使用。希望大佬们可以解决这个问题。

**Comment by HaoranShivs** [comment]
> 我正在尝试移植yolov8-pose，使用的是Ultralytics的预训练模型和手册里边所写的标准模型转化方式，转化过程没有报错。但是我遇到了问题，我模型最后出来结果的人体检测框和关键点出现按比例缩小（如缩小2-3倍），位置发生了漂移，与图中的人体和关键点不匹配，也出现了在图中均匀分散的冗余结果（如多了11倍的检测框）。但是所检测的关键点之间的关系确实正确的，即可以看出姿势的检测是对的。如下图。 ![R-C](https://private-user-images.githubusercontent.com/44091523/329579718-37c6e96c-90d3-4f30-8b14-8a96cce29bf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTEyNzUsIm5iZiI6MTcxNTY5MDk3NSwicGF0aCI6Ii80NDA5MTUyMy8zMjk1Nzk3MTgtMzdjNmU5NmMtOTBkMy00ZjMwLThiMTQtOGE5NmNjZTI5YmYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEyNDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTk0NjZlYjIyOTFiZDRhOThlZGM1YWUwMjdjZTMzNGM1NzVhYWVkY2NlZThkNWIwY2QyZjUyOGFmODRiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zR-enkMF30nc7jZ9jtjHokaJ6eRRM3e38FYnQopF1I0) 我控制变量验证过，不是图片前处理和后处理的问题，这个可以保证。希望大佬们可以解决这个问题。

已解决，没仔细看文本，推理的数据要NHWC输入的，我搞成NCHW了/

**Comment by HaoranShivs** [comment]
> 可以方便问一下您是怎么做转换的吗？我使用[https://github.com/airockchip/ultralytics_yolov8.git对yolov8s-pose转换为onnx的时候，转换失败了，seg是可以成功的](https://github.com/airockchip/ultralytics_yolov8.git%E5%AF%B9yolov8s-pose%E8%BD%AC%E6%8D%A2%E4%B8%BAonnx%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E8%BD%AC%E6%8D%A2%E5%A4%B1%E8%B4%A5%E4%BA%86%EF%BC%8Cseg%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%88%90%E5%8A%9F%E7%9A%84)

就使用ultralytics模型自带的一个export功能，详情看https://docs.ultralytics.com/tasks/pose/
最右边有一栏export，看了就懂了。

**Comment by AI-LLM2** [comment]
> 我正在尝试移植yolov8-pose，使用的是Ultralytics的预训练模型和手册里边所写的标准模型转化方式，转化过程没有报错。但是我遇到了问题，我模型最后出来结果的人体检测框和关键点出现按比例缩小（如缩小2-3倍），位置发生了漂移，与图中的人体和关键点不匹配，也出现了在图中均匀分散的冗余结果（如多了11倍的检测框）。但是所检测的关键点之间的关系确实正确的，即可以看出姿势的检测是对的。如下图。 ![R-C](https://private-user-images.githubusercontent.com/44091523/329579718-37c6e96c-90d3-4f30-8b14-8a96cce29bf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ0NTEsIm5iZiI6MTcyMjI2NDE1MSwicGF0aCI6Ii80NDA5MTUyMy8zMjk1Nzk3MTgtMzdjNmU5NmMtOTBkMy00ZjMwLThiMTQtOGE5NmNjZTI5YmYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE0NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MGQ0NzRjODZiZDAwNzQzZWQ3NGQ1ZmE1MTllMDZmOWQzMzBiOTVjYmFjZjc2MzUzNTI0NjEwZGU5ZWU2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2P_iSkQU0JdP_HNvep8RgAaE1bTp6cs5FXnQUKIBVg) 我控制变量验证过，不是图片前处理和后处理的问题，这个可以保证。希望大佬们可以解决这个问题。

请问后处理的代码是参考哪里修改的。目前我想把yolov8 psoe移植到rv1126上面。

**Comment by HaoranShivs** [comment]
> > 我正在尝试移植yolov8-pose，使用的是Ultralytics的预训练模型和手册里边所写的标准模型转化方式，转化过程没有报错。但是我遇到了问题，我模型最后出来结果的人体检测框和关键点出现按比例缩小（如缩小2-3倍），位置发生了漂移，与图中的人体和关键点不匹配，也出现了在图中均匀分散的冗余结果（如多了11倍的检测框）。但是所检测的关键点之间的关系确实正确的，即可以看出姿势的检测是对的。如下图。 ![R-C](https://private-user-images.githubusercontent.com/44091523/329579718-37c6e96c-90d3-4f30-8b14-8a96cce29bf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ0NTEsIm5iZiI6MTcyMjI2NDE1MSwicGF0aCI6Ii80NDA5MTUyMy8zMjk1Nzk3MTgtMzdjNmU5NmMtOTBkMy00ZjMwLThiMTQtOGE5NmNjZTI5YmYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE0NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MGQ0NzRjODZiZDAwNzQzZWQ3NGQ1ZmE1MTllMDZmOWQzMzBiOTVjYmFjZjc2MzUzNTI0NjEwZGU5ZWU2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2P_iSkQU0JdP_HNvep8RgAaE1bTp6cs5FXnQUKIBVg) 我控制变量验证过，不是图片前处理和后处理的问题，这个可以保证。希望大佬们可以解决这个问题。
> 
> 请问后处理的代码是参考哪里修改的。目前我想把yolov8 psoe移植到rv1126上面。

还是Ultralytics官方开源的后处理代码

**Comment by AI-LLM2** [comment]
请问目前跑通的是rv1126还是rk3588？方便把这能跑通的代码发出来参考一下吗？

**Comment by HaoranShivs** [comment]
> 请问目前跑通的是rv1126还是rk3588？方便把这能跑通的代码发出来参考一下吗？

rk3566，不过和rk3588同款npu，就是少了3个核心。代码没必要发，Ultralytics官方开源的代码，你找找对应后处理代码的路径，import一下就行了

**Comment by airockchip** [comment]
v2.1.0已支持yolov8 pose及yolov8 obb

**Comment by aodexiusi1997** [comment]
> > > 我正在尝试移植yolov8-pose，使用的是Ultralytics的预训练模型和手册里边所写的标准模型转化方式，转化过程没有报错。但是我遇到了问题，我模型最后出来结果的人体检测框和关键点出现按比例缩小（如缩小2-3倍），位置发生了漂移，与图中的人体和关键点不匹配，也出现了在图中均匀分散的冗余结果（如多了11倍的检测框）。但是所检测的关键点之间的关系确实正确的，即可以看出姿势的检测是对的。如下图。 ![R-C](https://private-user-images.githubusercontent.com/44091523/329579718-37c6e96c-90d3-4f30-8b14-8a96cce29bf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ0NTEsIm5iZiI6MTcyMjI2NDE1MSwicGF0aCI6Ii80NDA5MTUyMy8zMjk1Nzk3MTgtMzdjNmU5NmMtOTBkMy00ZjMwLThiMTQtOGE5NmNjZTI5YmYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE0NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MGQ0NzRjODZiZDAwNzQzZWQ3NGQ1ZmE1MTllMDZmOWQzMzBiOTVjYmFjZjc2MzUzNTI0NjEwZGU5ZWU2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2P_iSkQU0JdP_HNvep8RgAaE1bTp6cs5FXnQUKIBVg) 我控制变量验证过，不是图片前处理和后处理的问题，这个可以保证。希望大佬们可以解决这个问题。
> > 
> > 
> > 请问后处理的代码是参考哪里修改的。目前我想把yolov8 psoe移植到rv1126上面。
> 
> 还是Ultralytics官方开源的后处理代码

大佬，你好，我现在 比较急需要移植一下v8-pose，请问你是在[ultralytics](https://github.com/ultralytics/ultralytics)剥离出的后处理代码吗？同时在导出onnx的时候有没有对侦测头进行拆分呢！？

**Comment by HaoranShivs** [comment]
嗯，和你想的一致发自我的平板-------- 原始邮件 --------发件人： aodexiusi1997 ***@***.***>日期： 2024年8月16日周五 中午11:03收件人： airockchip/rknn_model_zoo ***@***.***>抄送： Haoran Shi ***@***.***>, Comment ***@***.***>主    题： Re: [airockchip/rknn_model_zoo] 请问一下能否适配一下yolov8-pose,对我们很有用，谢谢。 (Issue #97)



我正在尝试移植yolov8-pose，使用的是Ultralytics的预训练模型和手册里边所写的标准模型转化方式，转化过程没有报错。但是我遇到了问题，我模型最后出来结果的人体检测框和关键点出现按比例缩小（如缩小2-3倍），位置发生了漂移，与图中的人体和关键点不匹配，也出现了在图中均匀分散的冗余结果（如多了11倍的检测框）。但是所检测的关键点之间的关系确实正确的，即可以看出姿势的检测是对的。如下图。  我控制变量验证过，不是图片前处理和后处理的问题，这个可以保证。希望大佬们可以解决这个问题。

请问后处理的代码是参考哪里修改的。目前我想把yolov8 psoe移植到rv1126上面。

还是Ultralytics官方开源的后处理代码

大佬，你好，我现在 比较急需要移植一下v8-pose，请问你是在ultralytics剥离出的后处理代码吗？同时在导出onnx的时候有没有对侦测头进行拆分呢！？

**Comment by WN-Wolf** [comment]
> > 我正在尝试移植yolov8-pose，使用的是Ultralytics的预训练模型和手册里边所写的标准模型转化方式，转化过程没有报错。但是我遇到了问题，我模型最后出来结果的人体检测框和关键点出现按比例缩小（如缩小2-3倍），位置发生了漂移，与图中的人体和关键点不匹配，也出现了在图中均匀分散的冗余结果（如多了11倍的检测框）。但是所检测的关键点之间的关系确实正确的，即可以看出姿势的检测是对的。如下图。 ![R-C](https://private-user-images.githubusercontent.com/44091523/329579718-37c6e96c-90d3-4f30-8b14-8a96cce29bf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTEyNzUsIm5iZiI6MTcxNTY5MDk3NSwicGF0aCI6Ii80NDA5MTUyMy8zMjk1Nzk3MTgtMzdjNmU5NmMtOTBkMy00ZjMwLThiMTQtOGE5NmNjZTI5YmYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEyNDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTk0NjZlYjIyOTFiZDRhOThlZGM1YWUwMjdjZTMzNGM1NzVhYWVkY2NlZThkNWIwY2QyZjUyOGFmODRiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zR-enkMF30nc7jZ9jtjHokaJ6eRRM3e38FYnQopF1I0) 我控制变量验证过，不是图片前处理和后处理的问题，这个可以保证。希望大佬们可以解决这个问题。
> 
> 已解决，没仔细看文本，推理的数据要NHWC输入的，我搞成NCHW了/

多谢，我也是遇到相同的问题，然后终于解决了！！！

**Comment by 1314520gu** [comment]
请问c++代码的训练自己的模型，发生检测框和关键点集体漂移，怎么解决。

**Comment by 1314520gu** [comment]
请问rk588 c++代码 进行推理。使用的是自己训练的模型。 检测时候发生检测框和关键点集体漂移，怎么解决。
