### ISSUE TITLE
在rv1126上使用ppocr时，如果使用常规rknn模型不会报错，但是加载时间很久。如果使用预编译模型，将无法得到结果。

### ISSUE THREAD

**Issue by 7288Fzq** [airockchip/rknn_model_zoo#98]
预编译模型输出：
![image](https://github.com/airockchip/rknn_model_zoo/assets/71710433/b587f2fa-b91f-4907-a31e-3d5e0a120fdd)
常规模型输出：
![image](https://github.com/airockchip/rknn_model_zoo/assets/71710433/a3992759-47f8-4074-ae41-6d1cb2c6e350)

希望尽快得到回复！感谢作者

**Comment by 7288Fzq** [comment]
问题解决了，预编译模型的环境需要1.7.5

**Comment by VeiLiang** [comment]
可以说得更清楚点么？我转换出来的PPOCR-Rec模型也是无法识别，数据都为0
